import './globals.css';
import { Inter } from 'next/font/google';
import ContentLayout from './components/ContentLayout';
import PageLayout from './components/PageLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const codeToRunOnClient = `
  (function initTheme() {
    const theme =
      typeof window !== 'undefined'
        ? localStorage.theme !== undefined
          ? localStorage.theme
          : 'dark'
        : 'dark';
          document
        .querySelector('html')
        .classList.replace(theme === 'dark' ? 'light' : 'dark', theme);
  })();`;

  return (
    <html lang='en' className='dark'>
      <head>
        <script
          id='theme-init'
          dangerouslySetInnerHTML={{ __html: codeToRunOnClient }}
        />
      </head>
      <body className={inter.className}>
        <PageLayout>
          <ContentLayout>{children}</ContentLayout>
        </PageLayout>
      </body>
    </html>
  );
}
